controllers/AdministradorasController.php
<?
namespace app\controllers;

use app\models\AdministradorasModel;
use Yii;
use yii\web\Controller;         
use yii\data\Pagination;

class AdministradorasController extends Controller {

    public static function listaAdministradorasSelect() {
        $query = AdministradorasModel::find();

        return $query->orderBy('id')->all();
    }

    public function actionCadastraAdministradoras() {
        return $this->render('cadastro-administradoras');
    }

    public function actionRealizaCadastroAdministradora(){
        $request = \yii::$app->request;

        if ($request->isPost) {
            $model = new AdministradorasModel();
            $model->attributes = $request->post();
            $model->save();
            return $this->redirect(['administradoras/listar-administradoras']);
        }

        return $this->render('cadastro-administradoras');
    }

    public function actionEditaAdministradoras() {
        $this->layout = false;
        $request = \yii::$app->request;

        if ($request->isGet) {
            $query = AdministradorasModel::find();
            $administradoras = $query->where(['id' => $request->get()])->one();
        }

        return $this->render('edita-administradoras', [
            'edit' => $administradoras
        ]);
    }

    public function actionRealizaEdicaoAdministradora(){
        $request = \yii::$app->request;

        if($request->isPost){
            $model = AdministradorasModel::findOne($request->post('id'));
            $model->attributes = $request->post();
            
            if ($model->update()){
                return $this->redirect(['administradoras/listar-administradoras']);
            } else{
                return $this->redirect(['administradoras/listar-administradoras']);
            }
        }
    }

    public function actionDeletaAdministradora(){
        $request = \yii::$app->request;

        if($request->isGet){
            $model = AdministradorasModel::findOne($request->get('id'));
            if($model->delete()){
                return $this->redirect(['administradoras/listar-administradoras', 'myAlert' => ['type' => 'success', 'msg' => 'Registro deletado com sucesso.']]);
            } else{
                return $this->redirect(['administradoras/listar-administradoras', 'myAlert' => ['type' => 'danger', 'msg' => 'Não foi possível deletar o registro.']]);
            }
        }
    }

    public function actionListarAdministradoras() {

        if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }

        $query = AdministradorasModel::find();

        $paginacao = new Pagination([
            'defaultPageSize' => 5,
            'totalCount' => $query->count(),
        ]);

        $administradoras = $query->orderBy('nomeAdm')
            ->offset($paginacao->offset)
            ->limit($paginacao->limit)
            ->all();
        
        return $this->render('listar-administradoras',[
            'administradoras' => $administradoras,
            'paginacao' => $paginacao,
        ]);

    }
    
}

?>

controllers/CondominiosController.php
<?
namespace app\controllers;

use app\models\CondominiosModel;
use Yii;
use yii\web\Controller;         
use yii\data\Pagination;


class CondominiosController extends Controller {

    public static function listaCondominiosSelect() {
        $query = CondominiosModel::find();

        return $query->orderBy('id')->all();
    }

    public function actionCadastroCondominios() {
        return $this->render('cadastro-condominios');
    }

    public function actionRealizaCadastroCondominios(){
        $request = \yii::$app->request;

        if ($request->isPost) {
            $model = new CondominiosModel();
            $model->attributes = $request->post();
            $model->save();
            return $this->redirect(['condominios/listar-condominios']);
        }

        return $this->render('cadastro-condominios');
    }

    public function actionEditaCondominios() {
        $this->layout = false;
        $request = \yii::$app->request;

        if ($request->isGet) {
            $query = CondominiosModel::find();
            $condominios = $query->where(['id' => $request->get()])->one();
        }

        return $this->render('edita-condominios', [
            'edit' => $condominios
        ]);
    }

    public function actionRealizaEdicaoCondominio(){
        $request = \yii::$app->request;

        if($request->isPost){
            $model = CondominiosModel::findOne($request->post('id'));
            $model->attributes = $request->post();
            
            if ($model->update()){
                return $this->redirect(['condominios/listar-condominios']);
            } else{
                return $this->redirect(['condominios/listar-condominios', 'msg' => 'erro']);
            }
        }
    }

    public function actionDeletaCondominios(){
        $request = \yii::$app->request;

        if($request->isGet){
            $model = CondominiosModel::findOne($request->get('id'));
            if($model->delete()){
                return $this->redirect(['condominios/listar-condominios', 'myAlert' => ['type' => 'success', 'msg' => 'Registro deletado com sucesso.']]);
            } else{
                return $this->redirect(['condominios/listar-condominios', 'myAlert' => ['type' => 'success', 'msg' => 'Não foi possível deletar o registro.']]);
            }
        }
    }
    
    public function actionListarCondominios() {

        if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }

        $query = (new \yii\db\Query())
        ->select(
        'cond.id,
        adm.nomeAdm as AdmNome,
        cond.nome,
        cond.qtblocos,
        cond.cep,
        cond.rua,
        cond.num,
        cond.bairro,
        cond.cidade,
        cond.estado,
        cond.dataCadastro'
        )
        ->from('jp_condominio cond')
        ->innerJoin('jp_administradora adm', 'adm.id = cond.from_administradora');

        $paginacao = new Pagination([
            'defaultPageSize' => 5,
            'totalCount' => $query->count(),
        ]);

        $condominios = $query->orderBy('nome')
            ->offset($paginacao->offset)
            ->limit($paginacao->limit)
            ->all();
        
        return $this->render('listar-condominios',[
            'condominios' => $condominios,
            'paginacao' => $paginacao,
        ]);

    }
    
}

?>

controllers/UnidadesController.php
<?
namespace app\controllers;

use app\models\UnidadesModel;
use Yii;
use yii\web\Controller;         
use yii\data\Pagination;


class UnidadesController extends Controller {

    public static function listaUnidadesSelect($from) {
        $query = UnidadesModel::find();
        $data = $query->where(['from_bloco' => $from])->orderBy('numUnd')->all();
        return $data;
    }

    public function actionListaUnidadesApi(){
        $request = \yii::$app->request;
        $query = UnidadesModel::find();
        $data = $query->where(['from_bloco' => $request->post()])->orderBy('numUnd')->all();

        $dadosUnd = array();
        $i = 0;

        foreach($data as $d) {
            $dadosUnd[$i]['id'] = $d['id'];
            $dadosUnd[$i]['numUnd'] = $d['numUnd'];
            $i++;
        }
        return json_encode($dadosUnd);
    }

    public function actionCadastroUnidades() {
        return $this->render('cadastro-unidades');
    }

    public function actionRealizaCadastroUnidades(){
        $request = \yii::$app->request;

        if ($request->isPost) {
            $model = new UnidadesModel();
            $model->attributes = $request->post();
            $model->save();
            return $this->redirect(['unidades/listar-unidades']);
        }

        return $this->render('cadastro-unidades');
    }

    public function actionEditaUnidades() {
        $this->layout = false;
        $request = \yii::$app->request;

        if ($request->isGet) {
            $query = UnidadesModel::find();
            $unidades = $query->where(['id' => $request->get()])->one();
        }

        return $this->render('edita-unidades', [
            'edit' => $unidades
        ]);
    }

    public function actionRealizaEdicaoUnidade(){
        $request = \yii::$app->request;

        if($request->isPost){
            $model = UnidadesModel::findOne($request->post('id'));
            $model->attributes = $request->post();
            
            if ($model->update()){
                return $this->redirect(['unidades/listar-unidades']);
            } else{
                return $this->redirect(['unidades/listar-unidades', 'msg' => 'erro']);
            }
        }
    }

    public function actionDeletaUnidade(){
        $request = \yii::$app->request;

        if($request->isGet){
            $model = UnidadesModel::findOne($request->get('id'));
            if($model->delete()){
                return $this->redirect(['unidades/listar-unidades', 'myAlert' => ['type' => 'success', 'msg' => 'Registro deletado com sucesso.']]);
            } else{
                return $this->redirect(['unidades/listar-unidades', 'myAlert' => ['type' => 'success', 'msg' => 'Não foi possível deletar o registro.']]);
            }
        }
    }

    public function actionListarUnidades() {

        if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }

        $query = (new \yii\db\Query())
        ->select('unidade.id, 
        unidade.numUnd, 
        bloco.nomeBloco, 
        condo.nome, 
        unidade.from_condominio, 
        unidade.from_bloco, 
        unidade.metragem, 
        unidade.qtVagas,
        unidade.dataCadastro'
        )
        ->from('jp_unidade unidade')
        ->innerJoin('jp_bloco bloco', 'bloco.id = unidade.from_bloco')
        ->innerJoin('jp_condominio condo', 'condo.id = unidade.from_condominio');

        $paginacao = new Pagination([
            'defaultPageSize' => 5,
            'totalCount' => $query->count(),
        ]);

        $unidades = $query->orderBy('numUnd')
            ->offset($paginacao->offset)
            ->limit($paginacao->limit)
            ->all();
        
        return $this->render('listar-unidades',[
            'unidades' => $unidades,
            'paginacao' => $paginacao,
        ]);

    }
    
}

?>

views/layouts/main.php
<?php

/** @var yii\web\View $this */
/** @var string $content */

use app\assets\AppAsset;
use app\widgets\Alert;
use yii\bootstrap4\Breadcrumbs;
use yii\bootstrap4\Html;
use yii\bootstrap4\Nav;
use yii\bootstrap4\NavBar;
use kartik\icons\FontAwesomeAsset;

FontAwesomeAsset::register($this);
AppAsset::register($this);

?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>" class="h-100">
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="d-flex flex-column h-100">
<?php $this->beginBody() ?>

<header>
    <?php
    NavBar::begin([
        'brandLabel' => '<img src="img/Logo-site.png" width="70px"/>',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar navbar-expand-md znavbar-dark bg-dark fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav'],
        'items' => [
            [
                'label' => 'Inicio',
                'url' => ['index']
            ],
            [
                'label' => 'Administradoras',
                'items' => [
                    [
                        'label' => 'Listar',
                        'url' => ['administradoras/listar-administradoras']
                    ], [
                        'label' => 'Cadastrar Adm',
                        'url' => ['/administradoras/cadastra-administradoras']
                    ]
                ]
            ],
            [
                'label' => 'Condominios',
                'items' => [
                    [
                        'label' => 'Listar',
                        'url' => ['condominios/listar-condominios']
                    ], [
                        'label' => 'Cadastrar Condominios',
                        'url' => ['condominios/cadastro-condominios']
                    ]
                ]
            ],
            [
                'label' => 'Blocos',
                'items' => [
                    [
                        'label' => 'Listar',
                        'url' => ['blocos/listar-blocos']
                    ], [
                        'label' => 'Cadastrar Blocos',
                        'url' => ['blocos/cadastro-blocos']
                    ]
                ]
            ],
            [
                'label' => 'Unidade',
                'items' => [
                    [
                        'label' => 'Listar',
                        'url' => ['unidades/listar-unidades']
                    ], [
                        'label' => 'Cadastrar Unidade',
                        'url' => ['unidades/cadastro-unidades']
                    ]
                ]
            ],
            [
                'label' => 'Morador',
                'items' => [
                    [
                        'label' => 'Listar',
                        'url' => ['moradores/listar-moradores']
                    ], [
                        'label' => 'Cadastrar Morador',
                        'url' => ['moradores/cadastro-moradores']
                    ]
                ]
            ],
            [
                'label' => 'Conselho',
                'items' => [
                    [
                        'label' => 'Listar',
                        'url' => ['conselho/listar-conselho']
                    ], [
                        'label' => 'Cadastrar Conselho',
                        'url' => ['conselho/cadastrar-conselho']
                    ]
                ]
            ],

            Yii::$app->user->isGuest ? (
                ['label' => 'Login', 'url' => ['/site/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post', ['class' => 'form-inline'])
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->usuario . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            )
        ],
    ]);
    NavBar::end();
    ?>
</header>

<main role="main" class="flex-shrink-0 mt-5">
    <div class="container justify-content-center">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</main>

<footer class="footer fixed-bottom py-2 text-muted bg-dark text-light" style="height: 40px;">
    <div class="container">
        <p class="float-left">&copy; ApCoders <?= date('Y') ?></p>
        <p class="float-right">Jao</p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>