controllers/CondominiosController.php
<?
namespace app\controllers;

use app\models\CondominiosModel;
use Yii;
use yii\web\Controller;         
use yii\data\Pagination;


class CondominiosController extends Controller {

    public static function listaCondominiosSelect() {
        $query = CondominiosModel::find();

        return $query->orderBy('id')->all();
    }

    public function actionCadastroCondominios() {
        return $this->render('cadastro-condominios');
    }

    public function actionRealizaCadastroCondominios(){
        $request = \yii::$app->request;

        if ($request->isPost) {
            $model = new CondominiosModel();
            $model->attributes = $request->post();
            $model->save();
            return $this->redirect(['condominios/listar-condominios']);
        }

        return $this->render('cadastro-condominios');
    }

    public function actionEditaCondominios() {
        $this->layout = false;
        $request = \yii::$app->request;

        if ($request->isGet) {
            $query = CondominiosModel::find();
            $condominios = $query->where(['id' => $request->get()])->one();
        }

        return $this->render('edita-condominios', [
            'edit' => $condominios
        ]);
    }

    public function actionRealizaEdicaoCondominio(){
        $request = \yii::$app->request;

        if($request->isPost){
            $model = CondominiosModel::findOne($request->post('id'));
            $model->attributes = $request->post();
            
            if ($model->update()){
                return $this->redirect(['condominios/listar-condominios']);
            } else{
                return $this->redirect(['condominios/listar-condominios', 'msg' => 'erro']);
            }
        }
    }

    public function actionDeletaCondominios(){
        $request = \yii::$app->request;

        if($request->isGet){
            $model = CondominiosModel::findOne($request->get('id'));
            if($model->delete()){
                return $this->redirect(['condominios/listar-condominios', 'myAlert' => ['type' => 'success', 'msg' => 'Registro deletado com sucesso.']]);
            } else{
                return $this->redirect(['condominios/listar-condominios', 'myAlert' => ['type' => 'success', 'msg' => 'Não foi possível deletar o registro.']]);
            }
        }
    }
    
    public function actionListarCondominios() {

        if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }

        $query = (new \yii\db\Query())
        ->select(
        'cond.id,
        adm.nomeAdm as AdmNome,
        cond.nome,
        cond.qtblocos,
        cond.cep,
        cond.rua,
        cond.num,
        cond.bairro,
        cond.cidade,
        cond.estado,
        cond.dataCadastro'
        )
        ->from('jp_condominio cond')
        ->innerJoin('jp_administradora adm', 'adm.id = cond.from_administradora');

        $paginacao = new Pagination([
            'defaultPageSize' => 5,
            'totalCount' => $query->count(),
        ]);

        $condominios = $query->orderBy('nome')
            ->offset($paginacao->offset)
            ->limit($paginacao->limit)
            ->all();
        
        return $this->render('listar-condominios',[
            'condominios' => $condominios,
            'paginacao' => $paginacao,
        ]);

    }
    
}

?>

views/condominios/cadastro-condominios.php
<?
use app\components\estadosComponent;
use yii\helpers\Html;
use yii\widgets\LinkPager;
use yii\helpers\Url;
use app\controllers\AdministradorasController;
?>

<h1 class="text-center text-dark">Cadastro de Condominios</h1>

<form id="form-condo" class="col-12 py-2 mt-4 mb-4 rounded shadow" action="<?= Url::to(['condominios/realiza-cadastro-condominios']); ?>" method="post">
    <input class="col col-12 mt-2 form-control" type="text" name="nome" value="" placeholder="Nome" required>
    <input class="col col-12 mt-2 form-control" type="text" name="qtblocos" value="" placeholder="Quantidade de Blocos" required>

    <input class="col col-12 mt-4 form-control" type="text" name="rua" value="" placeholder="Rua" required>
    <input class="col col-12 mt-2 form-control" type="text" name="num" value="" placeholder="Número" required>
    <input class="col col-12 mt-2 form-control" type="text" name="bairro" value="" placeholder="Bairro" required>
    <input class="col col-12 mt-2 form-control" type="text" name="cidade" value="" placeholder="Cidade" required>

    <select name="from_administradora" class="col col-12 mt-2 form-control">
        <option value="">Selecione a Administradora</option>
        <?
        foreach (AdministradorasController::listaAdministradorasSelect() as $adm) {
        ?>
            <option value="<?= $adm['id'] ?>"><?= $adm['nomeAdm'] ?></option>
        <? } ?>
    </select>

    <select id="inputState" class="col col-12 mt-2 form-control" name="from_estado" required>
        <option value="">selecionar o Estado</option>
        <?
        foreach (estadosComponent::estados() as $sig => $uf) { ?>
            <option value="<?= $sig ?>"><?= $uf ?></option>
        <? } ?>
    </select>

    <input class="col col-12 mt-2 form-control" type="text" name="cep" value="" placeholder="Cep" required>

    <input type="hidden" name="<?= \yii::$app->request->csrfParam; ?>" value="<?= \yii::$app->request->csrfToken; ?>">

    <button class="btn btn-info mt-2 col col-12 buttonEnviar" type="submit">Enviar</button>
</form>

views/condominios/edita-condominios.php
<?
use app\components\estadosComponent;
use app\components\selectedComponent;
use yii\helpers\Html;
use yii\widgets\LinkPager;
use yii\helpers\Url;
use app\controllers\AdministradorasController;
?>

<h1 class="text-center text-dark">Cadastro de Condominios</h1>

<form id="form-condo" class="col-12 py-2 mt-4 mb-4 rounded shadow" action="<?= Url::to(['condominios/realiza-edicao-condominio']); ?>" method="post">

    <input class="col col-12 mt-2 form-control" type="text" name="nome" value="<?= $edit['nome'] ?>" placeholder="Nome" required>
    <input class="col col-12 mt-2 form-control" type="text" name="qtblocos" value="<?= $edit['qtblocos'] ?>" placeholder="Quantidade de Blocos" required>

    <input class="col col-12 mt-4 form-control" type="text" name="rua" value="<?= $edit['rua'] ?>" placeholder="Rua" required>
    <input class="col col-12 mt-2 form-control" type="text" name="num" value="<?= $edit['num'] ?>" placeholder="Número" required>
    <input class="col col-12 mt-2 form-control" type="text" name="bairro" value="<?= $edit['bairro'] ?>" placeholder="Bairro" required>
    <input class="col col-12 mt-2 form-control" type="text" name="cidade" value="<?= $edit['cidade'] ?>" placeholder="Cidade" required>

    <select name="from_administradora" class="col col-12 mt-2 form-control">
        <option value="">Selecione a Administradora</option>
        <?
        foreach (AdministradorasController::listaAdministradorasSelect() as $adm) {
        ?>
            <option value="<?= $adm['id'] ?>"<?=selectedComponent::isSelected($adm['id'], $edit['from_administradora'])?>><?= $adm['nomeAdm'] ?></option>
        <? } ?>
    </select>

    <select id="inputState" class="col col-12 mt-2 form-control" name="from_estado" required>
        <option value="">selecionar o Estado</option>
        <?
        foreach (estadosComponent::estados() as $sig => $uf) { ?>
            <option value="<?=$sig?>" <?=selectedComponent::isSelected($sig, $edit['estado'])?>><?= $uf ?></option>
        <? } ?>
    </select>

    <input class="col col-12 mt-2 form-control" type="text" name="cep" value="<?= $edit['cep'] ?>" placeholder="Cep" required>

    <input type="hidden" name="<?= \yii::$app->request->csrfParam; ?>" value="<?= \yii::$app->request->csrfToken; ?>">
    <input type="hidden" name="id" value="<?=$edit['id']?>">

    <button class="btn btn-info mt-2 buttonEnviar" type="submit">Salvar</button>
    <button type="button" class="btn btn-secondary mt-2" data-dismiss="modal">Fechar</button>
</form>

views/condominios/listar-condominios.php
<?

use app\components\alertComponent;
use app\components\maskComponent;
use app\components\modalComponent;
use yii\helpers\Html;
use yii\widgets\LinkPager;
use yii\helpers\url;

$url_site = Url::base($schema = true);

if(isset($_GET['myAlert'])){
    echo alertComponent::myAlert($_GET['myAlert']['type'],$_GET['myAlert']['msg']);
}

?>
<h1 class="text-center">Condominios</h1>
<ul>

<table class="container-fluid table table-dark table-striped table-responsive-md mt-4 shadow" id="listaCondo">
    <tr>
        <td>Nome</td>
        <td>Administradora</td>
        <td>Blocos</td>
        <td>Rua</td>
        <td>N°</td>
        <td>Bairro</td>
        <td>Cidade</td>
        <td>Estado</td>
        <td>Cep</td>
        <td>Data Cadastro</td>
        <td>Data Att</td>
        <td></td>
        <td align="center"><a href="<?=$url_site?>cadastroCondominio" class="btn btn-info">Cadastrar</a></td>
    </tr>

    <?
    foreach ($condominios as $dadosCondo) {
    ?>
        <tr data-id="<?=$dadosCondo['id']?>">
            <td><?= $dadosCondo['nome'] ?></td>
            <td><?= $dadosCondo['AdmNome'] ?></td>
            <td><?= $dadosCondo['qtblocos'] ?></td>
            <td><?= $dadosCondo['rua'] ?></td>
            <td><?= $dadosCondo['num'] ?></td>
            <td><?= $dadosCondo['bairro'] ?></td>
            <td><?= $dadosCondo['cidade'] ?></td>
            <td><?= $dadosCondo['estado'] ?></td>
            <td><?= maskComponent::mask($dadosCondo['cep'], 'cep') ?></td>
            <td><?=Yii::$app->formatter->format($dadosCondo['dataCadastro'],'date')?></td>
            <td align="center">
                <a href="<?=$url_site?>/index.php?r=condominios/edita-condominios&id=<?=$dadosCondo['id']?>" class="openModal"><i class="bi bi-pencil-square text-info"></i></a>
                <a href="<?=$url_site?>/index.php?r=condominios/deleta-condominios&id=<?=$dadosCondo['id']?>" data-id="<?= $dadosCondo['id'] ?>" class="removerCondo"><i class="bi bi-trash-fill text-info"></i></a>
            </td>
            <td></td>
            <td></td>
        </tr>
    <? } ?>
</table>

<div class="totalRegistros col-12 float-right">
    Total Registros <?=$paginacao->totalCount?>
</div>

<div class="row">
    <div class="col-12 mt-2">
            <?= LinkPager::widget(
            [
                'pagination' => $paginacao, 
                'linkContainerOptions' => [
                    'class' => 'page-item bg-dark text-info border-info'
                    ]
                , 'linkOptions' => [
                    'class' => 'page-link bg-dark text-info border-info'
                ],
                'disabledListItemSubTagOptions' => [
                    'class' => 'page-link bg-dark text-info border-info'
                ]
            ]
            ) ?>
    </div>
</div>

<?=modalComponent::initModal()?>