controllers/MoradoresController.php
<?
namespace app\controllers;

use app\components\alertComponent;
use app\models\MoradoresModel;
use Yii;
use yii\base\Component;
use yii\web\Controller;         
use yii\data\Pagination;


class MoradoresController extends Controller {

    public function actionCadastroMoradores() {
        return $this->render('cadastro-moradores');
    }

    public function actionRealizaCadastroMoradores(){
        $request = \yii::$app->request;

        if ($request->isPost) {
            $model = new MoradoresModel();
            $model->attributes = $request->post();
            $model->save();
            return $this->redirect(['moradores/cadastro-moradores']);
        }

        return $this->render('cadastro-moradores');
    }

    public function actionEditaMoradores() {
        $this->layout = false;
        $request = \yii::$app->request;

        if ($request->isGet) {
            $query = MoradoresModel::find();
            $moradores = $query->where(['id' => $request->get()])->one();
        }

        return $this->render('edita-moradores', [
            'edit' => $moradores
        ]);
    }

    public function actionRealizaEdicaoMorador(){
        $request = \yii::$app->request;

        if($request->isPost){
            $model = MoradoresModel::findOne($request->post('id'));
            $model->attributes = $request->post();
            
            if ($model->update()){
                return $this->redirect(['moradores/listar-moradores']);
            } else{
                return $this->redirect(['moradores/listar-moradores', 'msg' => 'erro']);
            }
        }
    }

    public function actionDeletaMorador(){
        $request = \yii::$app->request;

        if($request->isGet){
            $model = MoradoresModel::findOne($request->get('id'));
            if($model->delete()){
                return $this->redirect(['moradores/listar-moradores', 'myAlert' => ['type' => 'success', 'msg' => 'Registro deletado com sucesso.']]);
            } else{
                return $this->redirect(['moradores/listar-moradores', 'myAlert' => ['type' => 'danger', 'msg' => 'Não foi possível deletar o registro.']]);
            }
        }
    }

    public function actionListarMoradores() {

        if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }

        $query = (new \yii\db\Query())
        ->select('morador.id,  
        bloco.nomeBloco, 
        condo.nome,
        und.numUnd,
        morador.from_condominio,
        morador.from_bloco,
        morador.from_unidade,
        morador.nomeMorador,
        morador.dataCadastro,
        morador.cpf,
        morador.email,
        morador.telefone,
        morador.nascimento'
        )
        ->from('jp_morador morador')
        ->innerJoin('jp_bloco bloco', 'bloco.id = morador.from_bloco')
        ->innerJoin('jp_condominio condo', 'condo.id = morador.from_condominio')
        ->innerJoin('jp_unidade und', 'und.id = morador.from_unidade');

        $paginacao = new Pagination([
            'defaultPageSize' => 5,
            'totalCount' => $query->count(),
        ]);

        $moradores = $query->orderBy('nomeMorador')
            ->offset($paginacao->offset)
            ->limit($paginacao->limit)
            ->all();
        
        return $this->render('listar-moradores',[
            'moradores' => $moradores,
            'paginacao' => $paginacao,
        ]);

    }
    
}

?>

views/moradores/cadastro-moradores.php
<?
use app\components\generoComponent;
use app\components\modalComponent;
use app\controllers\BlocosController;
use app\controllers\CondominiosController;
use app\controllers\UnidadesController;
use kartik\datetime\DateTimePicker;
use yii\helpers\Url;
use kartik\widgets\FileInput;

?>

<h1 class="text-center text-dark">Cadastro de Moradores</h1>
<form id="form-clientes" class="col-12 px-2 py-2 mt-4 mb-4 rounded shadow" action="<?=Url::to(['moradores/realiza-cadastro-moradores']);?>" method="post">

    <select name="from_condominio" class="custom-select mt-2 fromCondominio">
        <option value="">Selecione o Condominio</option>
        <?
        foreach (CondominiosController::listaCondominiosSelect() as $condo) {
        ?>
            <option value="<?= $condo['id'] ?>"><?= $condo['nome'] ?></option>
        <? } ?>
    </select>

    <select name="from_bloco" class="fromBloco custom-select mt-2">

    </select>

    <select name="from_unidade" class="fromUnidade custom-select mt-2">

    </select>

    <input class="col col-12 mt-2 form-control" type="text" name="nomeMorador" value="" placeholder="Nome" required>

    <input class="col col-12 mt-2 form-control px-0 p-2" type="date" name="nascimento"  value="">

    
    <div class="col col-12 mt-2 form-group px-0">
            <?=generoComponent::genSelect('genero')?>
    </div>

    <input class="col col-12 mt-2 form-control" type="text" name="cpf" value="" placeholder="CPF" required>
    <input class="col col-12 mt-2 form-control" type="email" name="email" value="" placeholder="Email" required>
    <input class="col col-12 mt-2 form-control" type="text" name="telefone" value="" placeholder="Telefone">

    <input type="hidden" name="<?= yii::$app->request->csrfParam; ?>" value="<?= yii::$app->request->csrfToken; ?>">

    <button class="btn btn-info mt-2 col col-12 buttonEnviar" type="submit">Enviar</button>
</form>

</div>

views/moradores/edita-moradores.php
<?

use app\components\generoComponent;
use app\components\modalComponent;
use app\components\selectedComponent;
use app\controllers\BlocosController;
use app\controllers\CondominiosController;
use app\controllers\UnidadesController;
use kartik\datetime\DateTimePicker;
use yii\helpers\Url;
use kartik\widgets\FileInput;

?>

<h1 class="text-center text-dark">Cadastro de Moradores</h1>
<form id="form-clientes" class="col-12 px-2 py-2 mt-4 mb-4 rounded shadow" action="<?= Url::to(['moradores/realiza-edicao-morador']); ?>" method="post">

    <select name="from_condominio" class="custom-select mt-2 fromCondominio">
    <option value="">Selecione um Condomínio</option>
        <? 
        foreach(CondominiosController::listaCondominiosSelect() as $cond){?>
        <option value="<?=$cond['id']?>"<?=selectedComponent::isSelected($cond['id'], $edit['from_condominio'])?>><?=$cond['nome']?></option>
        <? } ?>
    </select>

    <select name="from_bloco" class="fromBloco custom-select mt-2">
        <?
        foreach (BlocosController::listaBlocosEdit($edit['from_condominio']) as $bloco) {
            echo '<option value="' . $bloco['id'] . '"' . selectedComponent::isSelected($bloco['id'], $edit['from_bloco']) . '>' . $bloco['nomeBloco'] . '</option>';
        }
        ?>
    </select>

    <select name="from_unidade" class="fromUnidade custom-select mt-2">
        <?
        foreach(UnidadesController::listaUnidadesSelect($edit['from_bloco']) as $und){
            echo '<option value="'.$und['id'].'"'.selectedComponent::isSelected($und['id'], $edit['from_unidade']).'>'.$und['numUnd'].'</option>';
        }
        ?>
    </select>

    <input class="col col-12 mt-2 form-control" type="text" name="nomeMorador" value="<?= $edit['nomeMorador'] ?>" placeholder="Nome" required>

    <input class="col col-12 mt-2 form-control px-0" type="date" name="nascimento"  value="<?= $edit['nascimento'] ?>">


    <div class="col col-12 mt-2 form-group px-0">
        <?= generoComponent::genSelect('genero', $edit['genero']) ?>
    </div>

    <input class="col col-12 mt-2 form-control" type="text" name="cpf" value="<?= $edit['cpf'] ?>" placeholder="CPF" required>
    <input class="col col-12 mt-2 form-control" type="email" name="email" value="<?= $edit['email'] ?>" placeholder="Email" required>
    <input class="col col-12 mt-2 form-control" type="text" name="telefone" value="<?= $edit['telefone'] ?>" placeholder="Telefone">

    <input type="hidden" name="<?= yii::$app->request->csrfParam; ?>" value="<?= yii::$app->request->csrfToken; ?>">
    <input type="hidden" name="id" value="<?=$edit['id']?>">

    <button class="btn btn-info mt-2 buttonEnviar" type="submit">Salvar</button>
    <button type="button" class="btn btn-secondary mt-2" data-dismiss="modal">Fechar</button>
</form>

</div>

views/moradores/listar-moradores.php
<?
use app\components\alertComponent;
use yii\helpers\Html;
use yii\widgets\LinkPager;
use yii\helpers\url;
use app\components\maskComponent;
use app\components\modalComponent;

$url_site = Url::base(true);

// echo alertComponent::myAlert('success', 'Testando', '?r=moradores%2Fcadastro-moradores');

if(isset($_GET['myAlert'])){
    echo alertComponent::myAlert($_GET['myAlert']['type'],$_GET['myAlert']['msg']);
}

?>
<h1 class="text-center">Moradores</h1>

<table class="col col-md-12 col-sm-10 table table-dark table-striped table-responsive-md table-responsive-lg mt-4 shadow" id="listaClientes">

    <tr>
        <td>Condominio</td>
        <td>Bloco</td>
        <td>Unidade</td>
        <td>Nome</td>
        <td>Documento</td>
        <td>Email</td>
        <td>Telefone</td>
        <td>Data Cadastro</td>
        <td>Data Atualizado</td>
        <td align="center"><a href="<?=$url_site?>cadastroMoradores" class="btn btn-info">Cadastrar</a></td>
    </tr>

    <?
    foreach ($moradores as $dados) {
    ?>
        <tr data-id="<?=$dados['id']?>">
            <td><?= $dados['nome'] ?></td>
            <td><?= $dados['nomeBloco'] ?></td>
            <td><?= $dados['numUnd'] ?></td>
            <td><?= $dados['nomeMorador'] ?></td>
            <td><?= maskComponent::mask($dados['cpf'], 'cpf') ?></td>
            <td><?= $dados['email'] ?></td>
            <td><?= maskComponent::mask($dados['telefone'], 'telefone') ?></td>
            <td><?=Yii::$app->formatter->format($dados['dataCadastro'],'date')?></td>
            <td align="center">
                <a href="<?=$url_site?>/index.php?r=moradores/edita-moradores&id=<?=$dados['id']?>" class="openModal"><i class="bi bi-pencil-square text-info"></i></a>
                <a href="<?=$url_site?>/index.php?r=moradores/deleta-morador&id=<?=$dados['id']?>" data-id="<?= $dados['id'] ?>" class="removerCliente"><i class="bi bi-trash-fill text-info"></i></a>
            </td>
            <td colspan="8"></td>
        </tr>
    <? } ?>
</table>  

<div class="totalRegistros col-12 float-right">
    Total Registros <?=$paginacao->totalCount?>
</div>

<div class="row">
    <div class="col-12 mt-2">
            <?= LinkPager::widget(
            [
                'pagination' => $paginacao, 
                'linkContainerOptions' => [
                    'class' => 'page-item bg-dark text-info border-info'
                    ]
                , 'linkOptions' => [
                    'class' => 'page-link bg-dark text-info border-info'
                ],
                'disabledListItemSubTagOptions' => [
                    'class' => 'page-link bg-dark text-info border-info'
                ]
            ]
            ) ?>
    </div>
</div>

<?=modalComponent::initModal()?>