controllers/AdministradorasController.php
<?
namespace app\controllers;

use app\models\AdministradorasModel;
use Yii;
use yii\web\Controller;         
use yii\data\Pagination;

class AdministradorasController extends Controller {

    public static function listaAdministradorasSelect() {
        $query = AdministradorasModel::find();

        return $query->orderBy('id')->all();
    }

    public function actionCadastraAdministradoras() {
        return $this->render('cadastro-administradoras');
    }

    public function actionRealizaCadastroAdministradora(){
        $request = \yii::$app->request;

        if ($request->isPost) {
            $model = new AdministradorasModel();
            $model->attributes = $request->post();
            $model->save();
            return $this->redirect(['administradoras/listar-administradoras']);
        }

        return $this->render('cadastro-administradoras');
    }

    public function actionEditaAdministradoras() {
        $this->layout = false;
        $request = \yii::$app->request;

        if ($request->isGet) {
            $query = AdministradorasModel::find();
            $administradoras = $query->where(['id' => $request->get()])->one();
        }

        return $this->render('edita-administradoras', [
            'edit' => $administradoras
        ]);
    }

    public function actionRealizaEdicaoAdministradora(){
        $request = \yii::$app->request;

        if($request->isPost){
            $model = AdministradorasModel::findOne($request->post('id'));
            $model->attributes = $request->post();
            
            if ($model->update()){
                return $this->redirect(['administradoras/listar-administradoras']);
            } else{
                return $this->redirect(['administradoras/listar-administradoras']);
            }
        }
    }

    public function actionDeletaAdministradora(){
        $request = \yii::$app->request;

        if($request->isGet){
            $model = AdministradorasModel::findOne($request->get('id'));
            if($model->delete()){
                return $this->redirect(['administradoras/listar-administradoras', 'myAlert' => ['type' => 'success', 'msg' => 'Registro deletado com sucesso.']]);
            } else{
                return $this->redirect(['administradoras/listar-administradoras', 'myAlert' => ['type' => 'danger', 'msg' => 'Não foi possível deletar o registro.']]);
            }
        }
    }

    public function actionListarAdministradoras() {

        if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }

        $query = AdministradorasModel::find();

        $paginacao = new Pagination([
            'defaultPageSize' => 5,
            'totalCount' => $query->count(),
        ]);

        $administradoras = $query->orderBy('nomeAdm')
            ->offset($paginacao->offset)
            ->limit($paginacao->limit)
            ->all();
        
        return $this->render('listar-administradoras',[
            'administradoras' => $administradoras,
            'paginacao' => $paginacao,
        ]);

    }
    
}

?>

views/administradoras/cadastro-administradoras.php
<?
use yii\helpers\Url;
?>

<div class="">

    <h1 class="text-center text-dark">Cadastro de Administradoras</h1>

        <div class="">
            <form id="form-adm" class="col-12 py-2 mt-4 mb-4 rounded shadow" action="<?=Url::to(['administradoras/realiza-cadastro-administradora']);?>" method="post">

                <input class="col col-12 mt-2 form-control" type="text" name="nomeAdm" value="" placeholder="Nome da Adm" required>
                
                <input class="col col-12 mt-2 form-control" type="text" name="cnpj" value="" placeholder="CNPJ"required>       

                <input type="hidden" name="<?=yii::$app->request->csrfParam;?>" value="<?=yii::$app->request->csrfToken;?>">

                <button class="btn btn-info mt-2 col col-12 buttonEnviar" type="submit">Enviar</button>
            </form>
        </div>
        
</div>

views/administradoras/edita-administradoras.php
<?
use yii\helpers\Url;
?>

<div class="">

    <h1 class="text-center text-dark">Cadastro de Administradoras</h1>

        <div class="">
            <form id="form-adm" class="col-12 py-2 mt-4 mb-4 rounded shadow" action="<?=Url::to(['administradoras/realiza-edicao-administradora']);?>" method="post">

                <input class="col col-12 mt-2 form-control" type="text" name="nomeAdm" value="<?= $edit['nomeAdm'] ?>" placeholder="Nome da Adm" required>
                
                <input class="col col-12 mt-2 form-control" type="text" name="cnpj" value="<?= $edit['cnpj'] ?>" placeholder="CNPJ"required>       

                <input type="hidden" name="<?=yii::$app->request->csrfParam;?>" value="<?=yii::$app->request->csrfToken;?>">
                <input type="hidden" name="id" value="<?=$edit['id']?>">

                <button class="btn btn-info mt-2 buttonEnviar" type="submit">Salvar</button>
                <button type="button" class="btn btn-secondary mt-2" data-dismiss="modal">Fechar</button>
            </form>
        </div>
        
</div>

views/administradoras/listar-administradoras.php
<?

use app\components\alertComponent;
use app\components\maskComponent;
use app\components\modalComponent;
use yii\helpers\Html;
use yii\widgets\LinkPager;
use yii\helpers\url;
use app\controllers\maskController;

$url_site = Url::base($schema = true);

if(isset($_GET['myAlert'])){
    echo alertComponent::myAlert($_GET['myAlert']['type'],$_GET['myAlert']['msg']);
}

?>
<h1 class="text-center">Administradoras</h1>
<ul>

<table class="col col-12 table table-striped table-dark table-responsive-md mt-5" id="listaClientes">
    <tr>
        <td>Nome</td>
        <td>CNPJ</td>
        <td>Data Cadastro</td>
        <td align="center"><a href="#" class="btn btn-info btn-sm">Adicionar</a></td>
    </tr>
    <? foreach ($administradoras as $dados) {?>
        <tr data-id="<?=$dados['id']?>">
            <td><?= $dados['nomeAdm'] ?></td>
            <td><?= maskComponent::mask($dados['cnpj'], 'cnpj') ?></td>
            <td><?=Yii::$app->formatter->format($dados['dataCadastro'],'date')?></td>
            <td align="center">
                <a href="<?=$url_site?>/index.php?r=administradoras/edita-administradoras&id=<?=$dados['id']?>" class="openModal"><i class="bi bi-pencil-square text-info"></i></a>
                <a href="<?=$url_site?>/index.php?r=administradoras/deleta-administradora&id=<?=$dados['id']?>" data-id="<?=$dados['id']?>" class="removerCliente"><i class="bi bi-trash-fill text-info"></i></a>
            </td>
        </tr>
    <? } ?>

</table>

<div class="totalRegistros col-12 float-right">
    Total Registros <?=$paginacao->totalCount?>
</div>

<div class="row">
    <div class="col-12 mt-2">
            <?= LinkPager::widget(
            [
                'pagination' => $paginacao, 
                'linkContainerOptions' => [
                    'class' => 'page-item bg-dark text-info border-info'
                    ]
                , 'linkOptions' => [
                    'class' => 'page-link bg-dark text-info border-info'
                ],
                'disabledListItemSubTagOptions' => [
                    'class' => 'page-link bg-dark text-info border-info'
                ]
            ]
            ) ?>
    </div>
</div>

<?=modalComponent::initModal()?>